/**
 * seedDetections.js — Detection records seed script
 *
 * Inserts pest/disease detection records into the `droneoperations` collection
 * with docType: "detection".
 *
 * Run once:  node seedDetections.js
 * Safe to re-run: uses $setOnInsert so existing records are skipped.
 */

require("dotenv").config();
const mongoose = require("mongoose");
const dns      = require("dns");

// Use Google DNS so MongoDB Atlas SRV lookups work in dev
dns.setServers(["8.8.8.8", "8.8.4.4"]);

const DroneOperation = require("./models/DroneOperation");

// ── Detection Seed Data ───────────────────────────────────────────────────────

const DETECTIONS = [
  {
    docType: "detection",
    detectionId: "DET-001",
    scanDate: new Date("2026-09-15"),
    crop: "Corn",
    region: "North Karnataka",
    fieldId: "FLD-01",
    fieldName: "Dharwad Block A",
    latitude: 15.4589,
    longitude: 75.0078,
    healthScore: 42,
    severity: "High",
    affectedAcreage: 4.2,
    estimatedLoss: 72000,
    disease: {
      name: "Leaf Blight",
      scientificName: "Exserohilum turcicum",
      confidence: 94,
      spreadRatePct: 12,
      firstDetected: "2026-09-10",
    },
    treatment: {
      product: "Azoxystrobin + Difenoconazole (Amistar Top)",
      preHealthScore: 42,
      postHealthScore: 71,
      cost: 3570,
      recoveryDays: 14,
      appliedDate: "2026-09-16",
    },
    cropHealth: {
      overallStatus: "At Risk",
      healthScore: 42,
      ndviAvg: 0.38,
      affectedArea: "1.7 acres (40%)",
      healthyArea: "2.5 acres (60%)",
      trend: "Declining",
      lastHealthyDate: "September 10, 2026",
    },
    detectedIssue: {
      name: "Leaf Blight & Leaf Spot Disease Complex",
      scientificName: "Exserohilum turcicum (Northern Leaf Blight) & Bipolaris maydis (Southern Leaf Spot)",
      confidence: 94,
      severity: "High",
      cropAffected: "Corn (Maize)",
      detectionMethod: "AI Multispectral + RGB Analysis",
      firstDetected: "September 10, 2026",
      spreadRate: "Rapid — 12% increase in 4 days",
    },
    whatIsIt: {
      summary: "Leaf Blight is a fungal disease caused by Exserohilum turcicum that severely impacts corn crops. It thrives in warm, humid environments and spreads rapidly through wind-borne spores.",
      details: [
        "Northern Corn Leaf Blight (NCLB) produces long, elliptical, grayish-green to tan lesions on leaves that can grow 2–15 cm in length.",
        "The disease thrives in temperatures of 22-30°C with high humidity.",
      ],
    },
    whyDidItHappen: {
      primaryCauses: [
        { cause: "High Humidity", detail: "85-95% relative humidity for 5 consecutive days.", icon: "💧" },
        { cause: "Warm Temperatures", detail: "Sustained 26-29°C in optimal fungal growth range.", icon: "🌡️" },
      ],
      environmentalFactors: { temperature: "27°C avg", humidity: "89% avg", rainfall: "142mm (10 days)" },
    },
    symptomsFound: [
      { symptom: "Long Elliptical Lesions on Corn Leaves", description: "Grayish-green to tan, cigar-shaped lesions 3–12 cm long.", severity: "High", prevalence: "72% of sampled plants" },
      { symptom: "Premature Leaf Yellowing", description: "Lower canopy showing accelerated senescence.", severity: "Moderate", prevalence: "45% of field area" },
    ],
    impactOnCrop: {
      yieldLoss: { estimated: "25–40%", detail: "Photosynthesis reduction from leaf damage." },
      qualityImpact: { grade: "Downgraded from A to C", detail: "Poor kernel development." },
      economicLoss: { estimated: "₹45,000 – ₹72,000", detail: "Based on current market rates." },
      timelineThreat: "Without intervention within 5-7 days, disease will spread to 80%+ of the field.",
      secondaryRisks: ["Susceptible to secondary infections.", "Reduced plant vigor."],
    },
    recommendedTreatment: {
      immediate: [
        { action: "Foliar Fungicide Application", product: "Azoxystrobin + Difenoconazole SC (Amistar Top)", dosage: "1 mL per liter", method: "Drone spray at 25L/acre", timing: "Within 48 hours", cost: "₹850/acre" },
      ],
      followUp: [
        { action: "Second Fungicide Spray", product: "Propiconazole 25% EC (Tilt)", dosage: "1 mL per liter", method: "Ground or drone sprayer", timing: "10-14 days later", cost: "₹600/acre" },
      ],
      totalEstimatedCost: "₹2,200/acre (₹9,240 total for 4.2 acres)",
    },
    preventionTips: [
      { tip: "Practice Crop Rotation", detail: "Rotate with legumes or rice every 2 seasons.", priority: "Essential", icon: "🔄" },
      { tip: "Use Resistant Varieties", detail: "Switch to Ht-gene resistant corn hybrids.", priority: "High", icon: "🛡️" },
    ],
    aiRecommendations: [
      { recommendation: "Schedule Immediate Drone Spray", detail: "Optimal spray window tomorrow 6-8 AM.", confidence: 96, type: "action" },
      { recommendation: "Predicted Recovery Timeline", detail: "Containment within 14 days with treatment.", confidence: 91, type: "forecast" },
    ],
  },
  {
    docType: "detection",
    detectionId: "DET-002",
    scanDate: new Date("2026-09-14"),
    crop: "Rice",
    region: "Central Tamil Nadu",
    fieldId: "FLD-02",
    fieldName: "Thanjavur North",
    latitude: 10.787,
    longitude: 79.1378,
    healthScore: 58,
    severity: "Moderate",
    affectedAcreage: 3.1,
    estimatedLoss: 38000,
    disease: {
      name: "Brown Spot",
      scientificName: "Bipolaris oryzae",
      confidence: 89,
      spreadRatePct: 7,
      firstDetected: "2026-09-08",
    },
    treatment: {
      product: "Mancozeb 75% WP",
      preHealthScore: 58,
      postHealthScore: 78,
      cost: 1800,
      recoveryDays: 18,
      appliedDate: "2026-09-15",
    },
    cropHealth: { overallStatus: "Moderate Risk", healthScore: 58, ndviAvg: 0.52, affectedArea: "1.2 acres (39%)", healthyArea: "1.9 acres (61%)", trend: "Stable", lastHealthyDate: "September 5, 2026" },
    detectedIssue: { name: "Brown Spot Disease", scientificName: "Bipolaris oryzae", confidence: 89, severity: "Moderate", cropAffected: "Rice (Paddy)", detectionMethod: "AI Multispectral Analysis", firstDetected: "September 8, 2026", spreadRate: "Moderate — 7% increase in 6 days" },
    whatIsIt: { summary: "Brown Spot is a fungal disease affecting rice, causing brown oval lesions on leaves, reducing grain quality and yield.", details: ["Caused by Bipolaris oryzae, common in nutrient-deficient soils.", "Worsens with potassium and nitrogen deficiency."] },
    symptomsFound: [{ symptom: "Brown Oval Lesions", description: "Small brown spots on leaves with gray centers.", severity: "Moderate", prevalence: "52% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "15–25%", detail: "Grain quality reduction." }, economicLoss: { estimated: "₹25,000 – ₹38,000", detail: "Market rate impact." }, timelineThreat: "Treatable within 10 days.", secondaryRisks: ["Grain discoloration."] },
    recommendedTreatment: { immediate: [{ action: "Fungicide Spray", product: "Mancozeb 75% WP", dosage: "2.5g/L", method: "Knapsack sprayer", timing: "Immediately", cost: "₹580/acre" }], followUp: [], totalEstimatedCost: "₹1,800 total" },
    preventionTips: [{ tip: "Balanced Fertilization", detail: "Ensure adequate potassium and nitrogen.", priority: "Essential", icon: "⚖️" }],
    aiRecommendations: [{ recommendation: "Apply foliar potassium supplement", detail: "Boost plant resistance.", confidence: 87, type: "action" }],
  },
  {
    docType: "detection",
    detectionId: "DET-003",
    scanDate: new Date("2026-09-16"),
    crop: "Chili",
    region: "Andhra Pradesh Coast",
    fieldId: "FLD-05",
    fieldName: "Guntur West Zone",
    latitude: 16.3067,
    longitude: 80.4365,
    healthScore: 28,
    severity: "Critical",
    affectedAcreage: 5.8,
    estimatedLoss: 145000,
    disease: {
      name: "Anthracnose",
      scientificName: "Colletotrichum capsici",
      confidence: 97,
      spreadRatePct: 18,
      firstDetected: "2026-09-06",
    },
    treatment: {
      product: "Carbendazim 50% WP",
      preHealthScore: 28,
      postHealthScore: 55,
      cost: 4200,
      recoveryDays: 21,
      appliedDate: "2026-09-17",
    },
    cropHealth: { overallStatus: "Critical", healthScore: 28, ndviAvg: 0.25, affectedArea: "3.5 acres (60%)", healthyArea: "2.3 acres (40%)", trend: "Declining Rapidly", lastHealthyDate: "September 1, 2026" },
    detectedIssue: { name: "Chili Anthracnose (Die-Back)", scientificName: "Colletotrichum capsici", confidence: 97, severity: "Critical", cropAffected: "Chili Pepper", detectionMethod: "AI RGB + Thermal Analysis", firstDetected: "September 6, 2026", spreadRate: "Very Rapid — 18% increase in 10 days" },
    whatIsIt: { summary: "Anthracnose is a devastating fungal disease of chili, causing sunken lesions on fruits and die-back of branches.", details: ["Most damaging in warm, rainy seasons.", "Fruit infection leads to complete crop loss if unchecked."] },
    symptomsFound: [{ symptom: "Sunken Lesions on Fruit", description: "Dark sunken spots with salmon-colored spore masses.", severity: "Critical", prevalence: "65% of fruits" }, { symptom: "Branch Die-Back", description: "Blackening and drying of shoot tips.", severity: "High", prevalence: "40% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "50–70%", detail: "Fruit infection renders harvest unmarketable." }, economicLoss: { estimated: "₹1,00,000 – ₹1,45,000", detail: "High-value chili crop." }, timelineThreat: "Requires immediate intervention.", secondaryRisks: ["Complete fruit rot.", "Seed transmission to next crop."] },
    recommendedTreatment: { immediate: [{ action: "Systemic Fungicide", product: "Carbendazim 50% WP", dosage: "1g/L", method: "Thorough canopy spray", timing: "Immediately", cost: "₹720/acre" }], followUp: [{ action: "Contact Fungicide", product: "Copper Oxychloride", dosage: "3g/L", method: "Spray", timing: "7 days later", cost: "₹500/acre" }], totalEstimatedCost: "₹4,200 total" },
    preventionTips: [{ tip: "Hot Water Seed Treatment", detail: "Treat seeds at 52°C for 30 minutes.", priority: "Essential", icon: "🌡️" }],
    aiRecommendations: [{ recommendation: "Harvest marketable fruits immediately", detail: "Salvage what can be sold before further damage.", confidence: 95, type: "action" }],
  },
  {
    docType: "detection",
    detectionId: "DET-004",
    scanDate: new Date("2026-09-12"),
    crop: "Cotton",
    region: "Vidarbha",
    fieldId: "FLD-03",
    fieldName: "Amravati East",
    latitude: 20.9374,
    longitude: 77.7796,
    healthScore: 65,
    severity: "Moderate",
    affectedAcreage: 6.5,
    estimatedLoss: 52000,
    disease: {
      name: "Bacterial Wilt",
      scientificName: "Ralstonia solanacearum",
      confidence: 86,
      spreadRatePct: 5,
      firstDetected: "2026-09-05",
    },
    treatment: {
      product: "Streptomycin Sulphate + Tetracycline",
      preHealthScore: 65,
      postHealthScore: 80,
      cost: 3200,
      recoveryDays: 16,
      appliedDate: "2026-09-13",
    },
    cropHealth: { overallStatus: "Moderate Risk", healthScore: 65, ndviAvg: 0.55, affectedArea: "2.6 acres (40%)", healthyArea: "3.9 acres (60%)", trend: "Slowly Declining", lastHealthyDate: "September 3, 2026" },
    detectedIssue: { name: "Bacterial Wilt", scientificName: "Ralstonia solanacearum", confidence: 86, severity: "Moderate", cropAffected: "Cotton (Bt Cotton)", detectionMethod: "AI Thermal + Visual Analysis", firstDetected: "September 5, 2026", spreadRate: "Slow — 5% increase in 7 days" },
    whatIsIt: { summary: "Bacterial Wilt is a soil-borne disease that blocks vascular tissue, causing wilting and death of plants.", details: ["Enters through root wounds.", "Persists in soil for years."] },
    symptomsFound: [{ symptom: "Sudden Wilting", description: "Plants wilt during hot afternoon hours.", severity: "Moderate", prevalence: "35% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "20–30%", detail: "Boll development affected." }, economicLoss: { estimated: "₹35,000 – ₹52,000", detail: "Cotton market rate impact." }, timelineThreat: "Manageable with immediate action.", secondaryRisks: ["Root rot secondary infection."] },
    recommendedTreatment: { immediate: [{ action: "Antibiotic Spray", product: "Streptomycin + Tetracycline", dosage: "0.5g/L", method: "Soil drench", timing: "Immediately", cost: "₹490/acre" }], followUp: [], totalEstimatedCost: "₹3,200 total" },
    preventionTips: [{ tip: "Soil Solarization", detail: "Cover soil with plastic during summer.", priority: "High", icon: "☀️" }],
    aiRecommendations: [{ recommendation: "Remove infected plants", detail: "Prevent spread to healthy plants.", confidence: 92, type: "action" }],
  },
  {
    docType: "detection",
    detectionId: "DET-005",
    scanDate: new Date("2026-09-17"),
    crop: "Wheat",
    region: "Rajasthan West",
    fieldId: "FLD-04",
    fieldName: "Barmer Sector 3",
    latitude: 25.7521,
    longitude: 71.3967,
    healthScore: 35,
    severity: "High",
    affectedAcreage: 8.2,
    estimatedLoss: 95000,
    disease: {
      name: "Rust",
      scientificName: "Puccinia triticina",
      confidence: 92,
      spreadRatePct: 15,
      firstDetected: "2026-09-10",
    },
    treatment: {
      product: "Propiconazole 25% EC (Tilt)",
      preHealthScore: 35,
      postHealthScore: 62,
      cost: 4900,
      recoveryDays: 12,
      appliedDate: "2026-09-18",
    },
    cropHealth: { overallStatus: "At Risk", healthScore: 35, ndviAvg: 0.32, affectedArea: "5.0 acres (61%)", healthyArea: "3.2 acres (39%)", trend: "Declining", lastHealthyDate: "September 6, 2026" },
    detectedIssue: { name: "Leaf Rust", scientificName: "Puccinia triticina", confidence: 92, severity: "High", cropAffected: "Wheat", detectionMethod: "AI Multispectral Analysis", firstDetected: "September 10, 2026", spreadRate: "Rapid — 15% increase in 7 days" },
    whatIsIt: { summary: "Wheat Leaf Rust is caused by the fungus Puccinia triticina, producing orange-brown pustules on leaves.", details: ["Wind-borne urediniospores can travel hundreds of kilometers.", "Most destructive wheat disease globally."] },
    symptomsFound: [{ symptom: "Orange-Brown Pustules", description: "Small circular pustules on leaf upper surface.", severity: "High", prevalence: "68% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "30–50%", detail: "Grain shriveling due to reduced photosynthesis." }, economicLoss: { estimated: "₹65,000 – ₹95,000", detail: "Wheat MSP-based estimate." }, timelineThreat: "Critical window of 5 days for treatment.", secondaryRisks: ["Grain quality downgrade."] },
    recommendedTreatment: { immediate: [{ action: "Triazole Fungicide", product: "Propiconazole 25% EC", dosage: "1 mL/L", method: "Boom sprayer", timing: "Within 24 hours", cost: "₹600/acre" }], followUp: [], totalEstimatedCost: "₹4,900 total" },
    preventionTips: [{ tip: "Plant Resistant Varieties", detail: "Use Lr-gene resistant wheat cultivars.", priority: "Essential", icon: "🛡️" }],
    aiRecommendations: [{ recommendation: "Alert neighboring fields", detail: "Wind-borne spore risk to adjacent wheat fields.", confidence: 89, type: "warning" }],
  },
  {
    docType: "detection",
    detectionId: "DET-006",
    scanDate: new Date("2026-09-13"),
    crop: "Soybean",
    region: "Vidarbha",
    fieldId: "FLD-03",
    fieldName: "Amravati East",
    latitude: 20.9320,
    longitude: 77.7850,
    healthScore: 72,
    severity: "Low",
    affectedAcreage: 2.0,
    estimatedLoss: 15000,
    disease: {
      name: "Powdery Mildew",
      scientificName: "Microsphaera diffusa",
      confidence: 82,
      spreadRatePct: 3,
      firstDetected: "2026-09-10",
    },
    treatment: {
      product: "Sulphur 80% WDG",
      preHealthScore: 72,
      postHealthScore: 88,
      cost: 1100,
      recoveryDays: 10,
      appliedDate: "2026-09-14",
    },
    cropHealth: { overallStatus: "Mild Risk", healthScore: 72, ndviAvg: 0.62, affectedArea: "0.8 acres (20%)", healthyArea: "3.2 acres (80%)", trend: "Stable", lastHealthyDate: "September 8, 2026" },
    detectedIssue: { name: "Powdery Mildew", scientificName: "Microsphaera diffusa", confidence: 82, severity: "Low", cropAffected: "Soybean", detectionMethod: "AI Visual Analysis", firstDetected: "September 10, 2026", spreadRate: "Slow — 3% increase in 3 days" },
    whatIsIt: { summary: "Powdery Mildew appears as white powdery coating on leaves, rarely causing severe damage in soybean.", details: ["Favored by cool nights and warm days.", "Usually self-limiting."] },
    symptomsFound: [{ symptom: "White Powdery Coating", description: "Thin white fungal growth on upper leaf surfaces.", severity: "Low", prevalence: "25% of canopy" }],
    impactOnCrop: { yieldLoss: { estimated: "5–10%", detail: "Minor photosynthesis reduction." }, economicLoss: { estimated: "₹10,000 – ₹15,000", detail: "Low impact." }, timelineThreat: "Not urgent. Monitor over 2 weeks.", secondaryRisks: ["Cosmetic damage to pods."] },
    recommendedTreatment: { immediate: [{ action: "Sulphur Spray", product: "Sulphur 80% WDG", dosage: "3g/L", method: "Knapsack sprayer", timing: "Within 5 days", cost: "₹550/acre" }], followUp: [], totalEstimatedCost: "₹1,100 total" },
    preventionTips: [{ tip: "Adequate Spacing", detail: "Ensure proper air circulation.", priority: "Moderate", icon: "📏" }],
    aiRecommendations: [{ recommendation: "Monitor — no urgent action needed", detail: "Disease is self-limiting in this crop.", confidence: 84, type: "forecast" }],
  },
  {
    docType: "detection",
    detectionId: "DET-007",
    scanDate: new Date("2026-09-18"),
    crop: "Rice",
    region: "North Karnataka",
    fieldId: "FLD-06",
    fieldName: "Bagalkot Plot B",
    latitude: 16.1806,
    longitude: 75.6961,
    healthScore: 31,
    severity: "Critical",
    affectedAcreage: 3.5,
    estimatedLoss: 88000,
    disease: {
      name: "Blast Disease",
      scientificName: "Magnaporthe oryzae",
      confidence: 96,
      spreadRatePct: 20,
      firstDetected: "2026-09-11",
    },
    treatment: {
      product: "Tricyclazole 75% WP",
      preHealthScore: 31,
      postHealthScore: 58,
      cost: 2800,
      recoveryDays: 15,
      appliedDate: "2026-09-19",
    },
    cropHealth: { overallStatus: "Critical", healthScore: 31, ndviAvg: 0.28, affectedArea: "2.5 acres (71%)", healthyArea: "1.0 acres (29%)", trend: "Declining Rapidly", lastHealthyDate: "September 7, 2026" },
    detectedIssue: { name: "Rice Blast", scientificName: "Magnaporthe oryzae", confidence: 96, severity: "Critical", cropAffected: "Rice (Paddy)", detectionMethod: "AI Multispectral + Thermal", firstDetected: "September 11, 2026", spreadRate: "Very Rapid — 20% in 7 days" },
    whatIsIt: { summary: "Rice Blast is the most destructive rice disease worldwide, caused by Magnaporthe oryzae.", details: ["Can destroy a rice crop within 2 weeks if uncontrolled.", "Attacks leaves, nodes, and panicles."] },
    symptomsFound: [{ symptom: "Diamond-Shaped Lesions", description: "Gray-green diamond-shaped spots on leaves.", severity: "Critical", prevalence: "75% of plants" }, { symptom: "Neck Rot", description: "Panicle neck turns brown and breaks.", severity: "Critical", prevalence: "30% of tillers" }],
    impactOnCrop: { yieldLoss: { estimated: "60–80%", detail: "Panicle infection leads to total yield loss." }, economicLoss: { estimated: "₹65,000 – ₹88,000", detail: "Rice procurement price impact." }, timelineThreat: "Must treat within 48 hours.", secondaryRisks: ["Complete crop failure if neck blast spreads."] },
    recommendedTreatment: { immediate: [{ action: "Blast-Specific Fungicide", product: "Tricyclazole 75% WP", dosage: "0.6g/L", method: "Drone spray", timing: "Within 24 hours", cost: "₹800/acre" }], followUp: [{ action: "Isoprothiolane spray", product: "Isoprothiolane 40% EC", dosage: "1.5 mL/L", method: "Ground sprayer", timing: "10 days later", cost: "₹650/acre" }], totalEstimatedCost: "₹2,800 total" },
    preventionTips: [{ tip: "Avoid Excess Nitrogen", detail: "High N makes plants susceptible.", priority: "Essential", icon: "⚖️" }],
    aiRecommendations: [{ recommendation: "Emergency aerial spray recommended", detail: "Ground application too slow for this spread rate.", confidence: 97, type: "action" }],
  },
  {
    docType: "detection",
    detectionId: "DET-008",
    scanDate: new Date("2026-09-11"),
    crop: "Corn",
    region: "Central Tamil Nadu",
    fieldId: "FLD-02",
    fieldName: "Thanjavur North",
    latitude: 10.7905,
    longitude: 79.1325,
    healthScore: 55,
    severity: "Moderate",
    affectedAcreage: 3.8,
    estimatedLoss: 42000,
    disease: {
      name: "Leaf Blight",
      scientificName: "Exserohilum turcicum",
      confidence: 88,
      spreadRatePct: 8,
      firstDetected: "2026-09-04",
    },
    treatment: {
      product: "Azoxystrobin + Difenoconazole (Amistar Top)",
      preHealthScore: 55,
      postHealthScore: 79,
      cost: 3200,
      recoveryDays: 13,
      appliedDate: "2026-09-12",
    },
    cropHealth: { overallStatus: "Moderate Risk", healthScore: 55, ndviAvg: 0.48, affectedArea: "1.5 acres (39%)", healthyArea: "2.3 acres (61%)", trend: "Stabilizing", lastHealthyDate: "September 1, 2026" },
    detectedIssue: { name: "Northern Corn Leaf Blight", scientificName: "Exserohilum turcicum", confidence: 88, severity: "Moderate", cropAffected: "Corn (Maize)", detectionMethod: "AI Multispectral Analysis", firstDetected: "September 4, 2026", spreadRate: "Moderate — 8% increase in 7 days" },
    whatIsIt: { summary: "Northern Corn Leaf Blight produces cigar-shaped lesions that reduce photosynthetic area.", details: ["Common in the Indian monsoon season."] },
    symptomsFound: [{ symptom: "Cigar-Shaped Lesions", description: "Tan-colored lesions 5-10 cm long.", severity: "Moderate", prevalence: "48% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "15–25%", detail: "Early-stage, containable." }, economicLoss: { estimated: "₹30,000 – ₹42,000", detail: "Based on corn procurement rates." }, timelineThreat: "7-day window for effective treatment.", secondaryRisks: ["Stalk rot if weakened."] },
    recommendedTreatment: { immediate: [{ action: "Fungicide Application", product: "Amistar Top", dosage: "1 mL/L", method: "Drone or ground spray", timing: "Within 3 days", cost: "₹850/acre" }], followUp: [], totalEstimatedCost: "₹3,200 total" },
    preventionTips: [{ tip: "Remove Crop Debris", detail: "Destroy previous season residue.", priority: "High", icon: "🧹" }],
    aiRecommendations: [{ recommendation: "Early containment possible", detail: "Treat now to prevent escalation to High severity.", confidence: 90, type: "forecast" }],
  },
  {
    docType: "detection",
    detectionId: "DET-009",
    scanDate: new Date("2026-09-19"),
    crop: "Cotton",
    region: "Andhra Pradesh Coast",
    fieldId: "FLD-05",
    fieldName: "Guntur West Zone",
    latitude: 16.3100,
    longitude: 80.4310,
    healthScore: 48,
    severity: "High",
    affectedAcreage: 7.0,
    estimatedLoss: 110000,
    disease: {
      name: "Bacterial Wilt",
      scientificName: "Ralstonia solanacearum",
      confidence: 90,
      spreadRatePct: 10,
      firstDetected: "2026-09-12",
    },
    treatment: {
      product: "Streptomycin Sulphate + Tetracycline",
      preHealthScore: 48,
      postHealthScore: 68,
      cost: 5600,
      recoveryDays: 20,
      appliedDate: "2026-09-19",
    },
    cropHealth: { overallStatus: "At Risk", healthScore: 48, ndviAvg: 0.42, affectedArea: "4.2 acres (60%)", healthyArea: "2.8 acres (40%)", trend: "Declining", lastHealthyDate: "September 8, 2026" },
    detectedIssue: { name: "Bacterial Wilt", scientificName: "Ralstonia solanacearum", confidence: 90, severity: "High", cropAffected: "Cotton", detectionMethod: "AI Thermal Analysis", firstDetected: "September 12, 2026", spreadRate: "Moderate — 10% in 7 days" },
    whatIsIt: { summary: "Bacterial wilt causes rapid wilting and death of cotton plants by blocking water-conducting vessels.", details: ["Soil-borne pathogen.", "Worse in waterlogged fields."] },
    symptomsFound: [{ symptom: "Sudden Wilting", description: "Plants wilt suddenly even with adequate moisture.", severity: "High", prevalence: "55% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "35–50%", detail: "Boll shedding from wilted plants." }, economicLoss: { estimated: "₹80,000 – ₹1,10,000", detail: "Cotton market impact." }, timelineThreat: "Urgent — 3 day window.", secondaryRisks: ["Soil contamination for next season."] },
    recommendedTreatment: { immediate: [{ action: "Antibiotic + Bio-agent", product: "Streptomycin + Trichoderma", dosage: "0.5g/L + 4g/L", method: "Soil drench", timing: "Immediately", cost: "₹800/acre" }], followUp: [], totalEstimatedCost: "₹5,600 total" },
    preventionTips: [{ tip: "Improve Drainage", detail: "Avoid waterlogging in cotton fields.", priority: "Essential", icon: "💧" }],
    aiRecommendations: [{ recommendation: "Soil testing recommended post-harvest", detail: "Check bacterial load before next planting.", confidence: 88, type: "planning" }],
  },
  {
    docType: "detection",
    detectionId: "DET-010",
    scanDate: new Date("2026-09-10"),
    crop: "Chili",
    region: "North Karnataka",
    fieldId: "FLD-01",
    fieldName: "Dharwad Block A",
    latitude: 15.4600,
    longitude: 75.0100,
    healthScore: 62,
    severity: "Moderate",
    affectedAcreage: 2.5,
    estimatedLoss: 35000,
    disease: {
      name: "Leaf Spot",
      scientificName: "Cercospora capsici",
      confidence: 85,
      spreadRatePct: 6,
      firstDetected: "2026-09-04",
    },
    treatment: {
      product: "Mancozeb 75% WP",
      preHealthScore: 62,
      postHealthScore: 82,
      cost: 1500,
      recoveryDays: 11,
      appliedDate: "2026-09-11",
    },
    cropHealth: { overallStatus: "Moderate Risk", healthScore: 62, ndviAvg: 0.54, affectedArea: "1.0 acres (40%)", healthyArea: "1.5 acres (60%)", trend: "Stable", lastHealthyDate: "September 2, 2026" },
    detectedIssue: { name: "Cercospora Leaf Spot", scientificName: "Cercospora capsici", confidence: 85, severity: "Moderate", cropAffected: "Chili Pepper", detectionMethod: "AI RGB Analysis", firstDetected: "September 4, 2026", spreadRate: "Moderate — 6% in 6 days" },
    whatIsIt: { summary: "Cercospora Leaf Spot creates circular spots with gray centers on chili foliage.", details: ["Common during monsoon season.", "Rarely fatal but reduces leaf area."] },
    symptomsFound: [{ symptom: "Circular Gray-Centered Spots", description: "Spots 1-2cm with dark margins on leaves.", severity: "Moderate", prevalence: "40% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "10–20%", detail: "Reduced photosynthetic capacity." }, economicLoss: { estimated: "₹25,000 – ₹35,000", detail: "Chili price impact." }, timelineThreat: "10-day treatment window.", secondaryRisks: ["Defoliation in severe cases."] },
    recommendedTreatment: { immediate: [{ action: "Contact Fungicide", product: "Mancozeb 75% WP", dosage: "2.5g/L", method: "Knapsack sprayer", timing: "Within 5 days", cost: "₹600/acre" }], followUp: [], totalEstimatedCost: "₹1,500 total" },
    preventionTips: [{ tip: "Remove Infected Leaves", detail: "Reduce inoculum source.", priority: "High", icon: "🧹" }],
    aiRecommendations: [{ recommendation: "Continue monitoring", detail: "Disease is manageable at current level.", confidence: 86, type: "forecast" }],
  },
  {
    docType: "detection",
    detectionId: "DET-011",
    scanDate: new Date("2026-09-16"),
    crop: "Wheat",
    region: "Rajasthan West",
    fieldId: "FLD-04",
    fieldName: "Barmer Sector 3",
    latitude: 25.7480,
    longitude: 71.4010,
    healthScore: 70,
    severity: "Low",
    affectedAcreage: 2.8,
    estimatedLoss: 18000,
    disease: {
      name: "Powdery Mildew",
      scientificName: "Blumeria graminis",
      confidence: 80,
      spreadRatePct: 4,
      firstDetected: "2026-09-13",
    },
    treatment: {
      product: "Sulphur 80% WDG",
      preHealthScore: 70,
      postHealthScore: 86,
      cost: 1400,
      recoveryDays: 9,
      appliedDate: "2026-09-17",
    },
    cropHealth: { overallStatus: "Mild Risk", healthScore: 70, ndviAvg: 0.60, affectedArea: "0.8 acres (29%)", healthyArea: "2.0 acres (71%)", trend: "Stable", lastHealthyDate: "September 11, 2026" },
    detectedIssue: { name: "Wheat Powdery Mildew", scientificName: "Blumeria graminis f. sp. tritici", confidence: 80, severity: "Low", cropAffected: "Wheat", detectionMethod: "AI Visual Analysis", firstDetected: "September 13, 2026", spreadRate: "Slow — 4% in 3 days" },
    whatIsIt: { summary: "Powdery Mildew on wheat produces white fungal growth on leaves, typically early in the season.", details: ["Favored by cool, humid mornings.", "Controlled easily with sulphur."] },
    symptomsFound: [{ symptom: "White Powdery Patches", description: "Superficial white fungal growth on leaves.", severity: "Low", prevalence: "22% of plants" }],
    impactOnCrop: { yieldLoss: { estimated: "5–10%", detail: "Minor impact if treated early." }, economicLoss: { estimated: "₹12,000 – ₹18,000", detail: "Low severity impact." }, timelineThreat: "Non-urgent. Treat within 10 days.", secondaryRisks: ["Minor only."] },
    recommendedTreatment: { immediate: [{ action: "Sulphur Dusting", product: "Sulphur 80% WDG", dosage: "3g/L", method: "Dusting or spray", timing: "Within a week", cost: "₹500/acre" }], followUp: [], totalEstimatedCost: "₹1,400 total" },
    preventionTips: [{ tip: "Avoid Dense Canopy", detail: "Ensure air circulation.", priority: "Moderate", icon: "📏" }],
    aiRecommendations: [{ recommendation: "Low priority — schedule when convenient", detail: "No urgency required.", confidence: 82, type: "forecast" }],
  },
  {
    docType: "detection",
    detectionId: "DET-012",
    scanDate: new Date("2026-09-18"),
    crop: "Rice",
    region: "Central Tamil Nadu",
    fieldId: "FLD-02",
    fieldName: "Thanjavur North",
    latitude: 10.7850,
    longitude: 79.1400,
    healthScore: 45,
    severity: "High",
    affectedAcreage: 4.5,
    estimatedLoss: 68000,
    disease: {
      name: "Blast Disease",
      scientificName: "Magnaporthe oryzae",
      confidence: 93,
      spreadRatePct: 16,
      firstDetected: "2026-09-12",
    },
    treatment: {
      product: "Tricyclazole 75% WP",
      preHealthScore: 45,
      postHealthScore: 70,
      cost: 3600,
      recoveryDays: 14,
      appliedDate: "2026-09-19",
    },
    cropHealth: { overallStatus: "At Risk", healthScore: 45, ndviAvg: 0.38, affectedArea: "2.7 acres (60%)", healthyArea: "1.8 acres (40%)", trend: "Declining", lastHealthyDate: "September 9, 2026" },
    detectedIssue: { name: "Rice Blast", scientificName: "Magnaporthe oryzae", confidence: 93, severity: "High", cropAffected: "Rice (Paddy)", detectionMethod: "AI Multispectral Analysis", firstDetected: "September 12, 2026", spreadRate: "Rapid — 16% in 6 days" },
    whatIsIt: { summary: "Rice Blast attacks all above-ground parts of the rice plant, most devastating to panicles.", details: ["Particularly severe in nitrogen-rich fields.", "Spreads rapidly in humid conditions."] },
    symptomsFound: [{ symptom: "Spindle-Shaped Leaf Lesions", description: "Gray-centered lesions with brown borders.", severity: "High", prevalence: "60% of leaves" }],
    impactOnCrop: { yieldLoss: { estimated: "40–60%", detail: "Panicle infection developing." }, economicLoss: { estimated: "₹50,000 – ₹68,000", detail: "Rice market rate impact." }, timelineThreat: "Critical — treat within 48 hours.", secondaryRisks: ["Neck blast risk increasing."] },
    recommendedTreatment: { immediate: [{ action: "Tricyclazole Spray", product: "Tricyclazole 75% WP", dosage: "0.6g/L", method: "Drone spray", timing: "Within 24 hours", cost: "₹800/acre" }], followUp: [], totalEstimatedCost: "₹3,600 total" },
    preventionTips: [{ tip: "Reduce Nitrogen Application", detail: "Excess nitrogen increases susceptibility.", priority: "Essential", icon: "⚖️" }],
    aiRecommendations: [{ recommendation: "Immediate drone mission required", detail: "Manual spraying too slow for this spread rate.", confidence: 94, type: "action" }],
  },
];

// ── Runner ────────────────────────────────────────────────────────────────────

async function upsert(records) {
  let inserted = 0, skipped = 0;
  for (const rec of records) {
    const result = await DroneOperation.updateOne(
      { detectionId: rec.detectionId },
      { $setOnInsert: rec },
      { upsert: true }
    );
    result.upsertedCount > 0 ? inserted++ : skipped++;
  }
  return { inserted, skipped };
}

async function seed() {
  console.log("\n🔬  Detection Records Seed Script");
  console.log("─────────────────────────────────────────────────────");

  await mongoose.connect(process.env.MONGO_URI);
  console.log("✅  Connected to MongoDB\n");

  const result = await upsert(DETECTIONS);
  console.log(`Detections (docType:'detection'): ${result.inserted} inserted, ${result.skipped} already existed`);

  const total = await DroneOperation.countDocuments({ docType: "detection" });
  console.log(`\n📦  Total detection docs: ${total}`);
  console.log("✅  Seed complete!\n");

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌  Seed failed:", err.message);
  process.exit(1);
});
